# -*- coding: utf-8 -*-
"""2448534_SPR_ETE3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdFW3QXe52CuMhYhBYq_7kwGZO4rMZ_x
"""

pip install pyttsx3

!apt-get update && apt-get install -y espeak-ng

"""Pre-requisite Task -"""

import pyttsx3
engine = pyttsx3.init()
def sayit(speak):
  engine.say(speak)
  engine.runAndWait()

speak_list = ["Talk", "Four"]
for i in speak_list:
  sayit(i)

"""### HMM Structural Analysis for TALK

TASK 1
"""

states = ["S1_t", "S2_ɔ", "S3_k"]
observations_vocab = ["t_obs", "aw_obs", "k_obs", "noise"]


obs_seq = ["t_obs", "aw_obs", "aw_obs", "k_obs"]


pi = {
    "S1_t": 1.0,
    "S2_ɔ": 0.0,
    "S3_k": 0.0
}

A = {
    "S1_t": {"S1_t": 0.1, "S2_ɔ": 0.9, "S3_k": 0.0},
    "S2_ɔ": {"S1_t": 0.0, "S2_ɔ": 0.7, "S3_k": 0.3},
    "S3_k": {"S1_t": 0.0, "S2_ɔ": 0.0, "S3_k": 1.0}
}


B = {
    "S1_t": {"t_obs": 0.9, "aw_obs": 0.05, "k_obs": 0.03, "noise": 0.02},
    "S2_ɔ": {"t_obs": 0.05, "aw_obs": 0.9,  "k_obs": 0.03, "noise": 0.02},
    "S3_k": {"t_obs": 0.02, "aw_obs": 0.05, "k_obs": 0.9,  "noise": 0.03},
}


def viterbi(obs, states, pi, A, B):
    T = len(obs)
    dp = [{}]
    backpointer = [{}]

    # Initialization (t = 0)
    for s in states:
        dp[0][s] = pi[s] * B[s].get(obs[0], 0.0)
        backpointer[0][s] = None

    # Induction
    for t in range(1, T):
        dp.append({})
        backpointer.append({})
        for curr in states:
            best_prob = 0.0
            best_prev = None
            emit_p = B[curr].get(obs[t], 0.0)
            for prev in states:
                trans_p = A[prev].get(curr, 0.0)
                prob = dp[t-1][prev] * trans_p * emit_p
                if prob > best_prob:
                    best_prob = prob
                    best_prev = prev
            dp[t][curr] = best_prob
            backpointer[t][curr] = best_prev

    # Termination: choose final state with max prob at time T-1
    last_t = T - 1
    final_state = max(states, key=lambda s: dp[last_t][s])
    final_prob = dp[last_t][final_state]

    # Backtrack
    path = [final_state]
    for t in range(last_t, 0, -1):
        prev_state = backpointer[t][path[-1]]
        path.append(prev_state)
    path.reverse()
    return path, final_prob


def expected_duration(p_self):
    if p_self >= 1.0:
        return float('inf')
    return 1.0 / (1.0 - p_self)

if __name__ == "__main__":
    best_path, best_prob = viterbi(obs_seq, states, pi, A, B)
    print("Observation sequence:", obs_seq)
    print("Best state path (Viterbi):", best_path)
    print("Path probability:", best_prob)

    # Expected durations
    print("\nExpected durations (in frames) from self-loop probabilities:")
    for s in states:
        p_self = A[s][s]
        print(f" {s}: p_self = {p_self:.2f} -> expected frames = {expected_duration(p_self):.3f}")

"""a. explain why backward transitions such as P(/k/ to
/t/) or P(/ɔː/ to /t/) must be zero. State the linguistic property of fixed
phoneme ordering that this constraint enforces for the word TALK.

ANS:
Backward transitions must be zero to enforce a Left-to-Right topology, ensuring the phonemes occur in a time moves forward without ever reverting to previous sounds.

b. Based on what you heard in the text to
speech output, explain what these values imply about the relative duration of the phoneme /ɔː/ compared to the shorter burst like
phoneme /t/ in the model.

ANS:
Self-transition probabilities determine duration; the high value for /ɔː/ implies a long, sustained vowel, while the low value for /t/ implies a short, transient burst.

### Viterbi Algorithm Implementation

Task 2
"""

states = ["F", "AO", "UH", "R"]
observations = ["f", "ao", "uh", "r"]
obs_sequence = ["f", "ao", "uh", "r"]

start_prob = {
    "F": 1.0,
    "AO": 0.0,
    "UH": 0.0,
    "R": 0.0
}

trans_prob = {
    "F":  {"F": 0.3, "AO": 0.7, "UH": 0.0, "R": 0.0},
    "AO": {"F": 0.0, "AO": 0.3, "UH": 0.7, "R": 0.0},
    "UH": {"F": 0.0, "AO": 0.0, "UH": 0.3, "R": 0.7},
    "R":  {"F": 0.0, "AO": 0.0, "UH": 0.0, "R": 1.0},
}

emit_prob = {
    "F":  {"f": 0.9, "ao": 0.1, "uh": 0.0, "r": 0.0},
    "AO": {"f": 0.0, "ao": 0.9, "uh": 0.1, "r": 0.0},
    "UH": {"f": 0.0, "ao": 0.1, "uh": 0.9, "r": 0.0},
    "R":  {"f": 0.0, "ao": 0.0, "uh": 0.1, "r": 0.9},
}

def viterbi(obs, states, start_prob, trans_prob, emit_prob):

    dp = [{}]
    path = {}

    # 1. Initialization
    for s in states:
        dp[0][s] = start_prob[s] * emit_prob[s][obs[0]]
        path[s] = [s]

    # 2. Dynamic Programming
    for t in range(1, len(obs)):
        dp.append({})
        new_path = {}

        for curr_state in states:
            # Choose the best previous state
            probabilities = []
            for prev_state in states:
                prob = dp[t-1][prev_state] * trans_prob[prev_state][curr_state] * emit_prob[curr_state][obs[t]]
                probabilities.append((prob, prev_state))

            # Best transition
            best_prob, best_prev_state = max(probabilities, key=lambda x: x[0])

            dp[t][curr_state] = best_prob
            new_path[curr_state] = path[best_prev_state] + [curr_state]

        path = new_path

    # 3. Final best state
    final_state = max(states, key=lambda s: dp[-1][s])
    return path[final_state], dp[-1][final_state]

best_path, best_prob = viterbi(obs_sequence, states, start_prob, trans_prob, emit_prob)
print("Best Path:", best_path)
print("Best Probability:", best_prob)

"""a. Write the general formula for computing δ1(i)
for any state i.


Ans: sigma1 = pi1 * bi​(O1​)


b1 - Emission probability for observing O1 given state i.

Explain why δ1(i) must be zero for all states except S1
in a strictly ordered pronunciation model.

Ans: In a strictly ordered pronouncitation, the change in transition probabilities might result in mispronounciation of the word, making it meaningless.

b. During the induction step, the Viterbi algorithm applies a
maximization operation when computing δt(i). Explain the key
difference this introduces compared to the probability summation used
in the forward procedure. Justify why maximization is required to
identify the single most probable phoneme sequence Q* rather than all
possible paths.

Ans:

In the Viterbi algorithm, the induction step uses maximization, not summation, because it aims to find the single most probable state (phoneme) sequence
𝑄
∗


Summation would combine probabilities from many paths and make it impossible to identify which specific path is the best.

Maximization ensures that at each time step only the highest-probability partial path is kept.

This allows the algorithm to backtrack at the end and recover the unique most likely phoneme sequence, rather than a mixture of all paths.

c. After computing all δT(i) values for T=4, the system uses the stored
path pointer variable ψt(i) to retrieve the decoded sequence (/f/, /oʊ/,
/r/, End). Describe the role of ψ and outline the backtracking process
that allows the system to reconstruct the optimal phoneme sequence
from the final time step back to the beginning.

ANS:

ψ records which previous state led to the best (most probable) path into state i at time t.
It maximises partial probabilities to reach the final goal state.
"""

